import Link from "../../components/ui/Link";

const leaders = [["Hemantha Sapumohotti", "Chief Executive Officer", "HS"], ["Linda Gray, MBA (UWS, Australia)", "Talent & Culture Director", "LG"], ["Dr. Tara Giovanna, MB, BCh, BAO (Hons)", "Director", "TG"], ["Melani White", "Operations Manager", "MW"], ["Angeline Cooke", "Senior Administrative Manager", "AC"]];
const awards = [["Five Star Award", "Two consecutive years"], ["Top 100 Employer Brands in Asia", "World HRD Congress, Singapore"], ["Best Employer Brand", "Nine consecutive years, 2016 to 2024"], ["Best Women Leadership", "Leadership recognition"], ["Four Star Award", "Recruitment excellence"], ["Excellence Award", "Service recognition"], ["Certified Training Partner", "Professional development"]];

export default function AboutPage() {
  return <main id="main" className="ei-about-page">
    <section className="ei-about-hero"><div className="container"><p className="ei-kicker">Since 1995</p><h1>Thirty years of opening doors across the world.</h1><p>Emerald Isle Manpower & Travel Services is an SLBFE-licensed recruitment agency connecting skilled people with global opportunity.</p></div></section>
    <section className="ei-about-story"><div className="container ei-about-story-grid"><div><h2>Built on trust. Designed around people.</h2></div><div><p>Every recruitment assignment is unique. Our specialist teams combine labour-market research, careful screening and close client collaboration to create the right fit for skills, culture and long-term success.</p><p>From Sri Lanka, our network extends through Nepal, Bangladesh, India, Pakistan, Indonesia, the Philippines, Kenya and Myanmar, supporting placements across the Middle East, Europe, Romania and Ireland.</p><Link className="ei-button ei-button-dark" href="/contact/">Talk to our team <span className="ei-button__icon-wrapper"><svg viewBox="0 0 14 15" fill="none" xmlns="http://www.w3.org/2000/svg" className="ei-button__icon-svg" width={10} height={10}><path d="M13.376 11.552l-.264-10.44-10.44-.24.024 2.28 6.96-.048L.2 12.56l1.488 1.488 9.432-9.432-.048 6.912 2.304.024z" fill="currentColor" /></svg><svg viewBox="0 0 14 15" fill="none" width={10} height={10} xmlns="http://www.w3.org/2000/svg" className="ei-button__icon-svg ei-button__icon-svg--copy"><path d="M13.376 11.552l-.264-10.44-10.44-.24.024 2.28 6.96-.048L.2 12.56l1.488 1.488 9.432-9.432-.048 6.912 2.304.024z" fill="currentColor" /></svg></span></Link></div></div></section>
    <section className="ei-beliefs"><div className="container"><div className="ei-belief-grid"><article><span>Vision</span><h2>To be recognised globally as an innovative and efficient human capital solutions partner.</h2></article><article><span>Mission</span><p>We enhance every client’s success and improve every employee’s quality of life through the dignity and power of gainful employment, delivering best-in-class human capital solutions.</p></article><article><span>Values</span><div className="ei-values"><strong>Respect</strong><strong>Diversity</strong><strong>Teamwork</strong><strong>Empowerment</strong><strong>Community</strong></div></article></div></div></section>
    <section className="ei-management" aria-labelledby="management-title"><div className="container"><div className="ei-title-row"><h2 id="management-title">The people guiding Emerald Isle.</h2><p>Experienced leadership, shared standards and a commitment to responsible recruitment.</p></div><div className="ei-leader-list">{leaders.map(([name, role, initials]) => <article key={name}><span>{initials}</span><div><h3>{name}</h3><p>{role}</p></div></article>)}</div></div></section>
    <section className="ei-awards" aria-labelledby="awards-title"><div className="container"><div className="ei-awards-head"><div><p className="ei-kicker">Seven distinctions</p><h2 id="awards-title">Recognition earned over time.</h2></div><p>Our awards and credentials reflect consistent service, ethical recruitment and a culture that values people.</p></div><div className="ei-award-list">{awards.map(([name, detail], index) => <article key={name}><span>{String(index + 1).padStart(2, "0")}</span><h3>{name}</h3><p>{detail}</p></article>)}</div></div></section>
    <section className="ei-license"><div className="container"><div><p>Licensed and accountable</p><h2>SLBFE License No. 1162</h2></div><p>We operate under the Sri Lanka Bureau of Foreign Employment and follow regulatory requirements for compliant, ethical international recruitment.</p></div></section>
  </main>;
}
